import { Attributes } from '@/types/apiResponseTypes/apiResopnses'


const attributesList = {
  "CML2_ARTICLE": "Артикул",
  // "ARTIKULY_V_NABORE": "Артикулы в комплекте",
  // "ARTIKULY_TOVAROV_DLYA_KOTORYKH_PODKHODIT_IZ_1S": "Артикулы товаров, для которых подходит, из 1С",
  "BACHOK_V_KOMPLEKTE": "Бачок в комплекте",
  "BEZOBODKOVYY": "Безободковый",
  "BRAND": "Бренд",
  "VERKHNIY_DUSH_V_KOMPLEKTE": "Верхний душ в комплекте",
  "VES_BRUTTO": "Вес брутто, кг",
  "VES_NETTO": "Вес нетто, кг",
  "VID_ZATVORA_SIFONA": "Вид затвора сифона",
  "VID_OSNOVANIYA_POD_RAKOVINU": "Вид основания под раковину",
  "VID_PODDONA": "Вид поддона",
  "VID_PODSVETKI": "Вид подсветки",
  "VID_RAKOVINY": "Вид раковины",
  "VID_RESHETKI": "Вид решетки",
  "VID_UPAKOVKI": "Вид упаковки",
  "VMESTIMOST_SHT": "Вместимость, шт.",
  "VNUTRENNYAYA_GLUBINA_MM": "Внутренняя глубина, мм",
  "VYLET_VERKHNEGO_DUSHA_MM": "Вылет верхнего душа, мм",
  "vypusk": "Выпуск",
  "VYSOTA_DOPOLNITELNOY_CHASHI_MM": "Высота дополнительной чаши, мм",
  "VYSOTA_IZLIVA": "Высота излива, см",
  "VYSOTA_INSTALLYATSII_MM": "Высота инсталляции, мм",
  "VYSOTA_OPOR_MM": "Высота опор, мм",
  "VYSOTA_PODDONA_MM": "Высота поддона, мм",
  "VYSOTA_PEDESTALA_MM": "Высота пьедестала, мм",
  "VYSOTA_S_OPOROY_MM": "Высота с опорой, мм",
  "VYSOTA_S_RAKOVINOY_MM": "Высота с раковиной, мм",
  "VYSOTA_STOYKI_MM": "Высота стойки, мм",
  "VYSOTA_UNITAZA_MM": "Высота унитаза, мм",
  "VYSOTA_UPAKOVKI": "Высота упаковки, м",
  "VYSOTA_CHASHI_MM": "Высота чаши, мм",
  "VYSOTA": "Высота, мм",
  "GARANTIYA": "Гарантия",
  "GARNATIYA_NA_TOVARY_KOMPLEKTA": "Гарантия на товары комплекта",
  "GIGIENICHESKIY_DUSH_V_KOMPLEKTE": "Гигиенический душ в комплекте",
  "GLUBINA_DOPOLNITELNOY_CHASHI_MM": "Глубина дополнительной чаши, мм",
  "GLUBINA_INSTALLYATSII_MM": "Глубина инсталляции, мм",
  "GLUBINA_PODDONA_MM": "Глубина поддона, мм",
  "GLUBINA_PEDESTALA_MM": "Глубина пьедестала, мм",
  "GLUBINA_UNITAZA_MM": "Глубина унитаза, мм",
  "GLUBINA_CHASHI_MM": "Глубина чаши, мм",
  "GLUBINA": "Глубина, мм",
  "GOTOVYE_OTVERTSTIYA_POD_SMESITEL": "Готовые отверстия под смеситель",
  "DERZHATEL_DLYA_DUSHEVOY_LEYKI_V_KOMPLEKTE": "Держатель душевой лейки в комплекте",
  "DIAMETR_DOPOLNITELNOY_CHASHI_MM": "Диаметр дополнительной чаши, мм",
  "DIAMETR_KERAMICHESKOGO_KARTRIDZHA_MM": "Диаметр картриджа, мм",
  "DIAMETR_OTVERSTIYA_POD_SMESITEL_MM": "Диаметр отверстия под смеситель, мм",
  "DIAMETR_PEREKHODNIKA_DLYA_SLIVA_MM": "Диаметр переходника для слива, мм",
  "DIAMETR_PODKLYUCHENIYA_K_KANALIZATSII_MM": "Диаметр подключения к канализации, мм",
  "DIAMETR_SLIVA_MM": "Диаметр слива, мм",
  "DIAMETR_CHASHI_MM": "Диаметр чаши, мм",
  "DIAMETR": "Диаметр, мм",
  "DLINA_VNESHNEY_CHASTI_MM": "Длина внешней части, мм",
  "DLINA_DOPOLNITELNOY_CHASHI_MM": "Длина дополнительной чаши, мм",
  "DLINA_IZLIVA": "Длина излива, см",
  "DLINA_INSTALLYATSII_MM": "Длина инсталляции, мм",
  "DLINA_UNITAZA_MM": "Длина унитаза, мм",
  "DLINA_UPAKOVKI": "Длина упаковки, м",
  "DLINA_CHASHI_MM": "Длина чаши, мм",
  "DLINA_SHLANGA_MM": "Длина шланга, мм",
  "DLINA": "Длина, мм",
  "DLYA_SIFONA_DIAMETROM_MM": "Для сифона диаметром, мм",
  "DOZATOR_V_KOMPLEKTE": "Дозатор в комплекте",
  "DONNYY_KLAPAN_V_KOMPLEKTE": "Донный клапан в комплекте",
  "DOPOLNITELNOE_OSNASHCHENIE": "Дополнительное оснащение",
  "DOPOLNITELNYE_PREIMUSHCHESTVA": "Дополнительные преимущества",
  "DOPOLNITELNYE_FUNKTSII": "Дополнительные функции",
  "REZERVED_STORE": "Зарезервировано",
  "IZMELCHITEL_OTKHODOV_V_KOMPLEKTE": "Измельчитель отходов в комплекте",
  "INSTRUKTSII": "Инструкции",
  "INFOGRAFIKA": "Инфографика",
  "ISPOLNENIE_IZLIVA": "Исполнение излива",
  "ISPOLNENIE_POLOTNA": "Исполнение полотна",
  "ISTOCHNIK_PITANIYA": "Источник питания",
  "KARKAS_V_KOMPLEKTE": "Каркас в комплекте",
  "MORE_PHOTO": "Картинки товара",
  "KNOPKA_SMYVA_V_KOMPLEKTE": "Кнопка смыва в комплекте",
  // "KOD_TNVED": "Код ТНВЭД",
  "KOLICHESTVO_V_INDIVIDUALNOY_UPAKOVKE_SHT": "Количество в индивидуальной упаковке, шт.",
  "KOLICHESTVO_DVEREY": "Количество дверей",
  "KOLICHESTVO_KRYUCHKOV_SHT": "Количество крючков, шт.",
  "KOLICHESTVO_OTVERSTIY_POD_RAKOVINU": "Количество отверстий под раковину",
  "KOLICHESTVO_OTVERSTIY_POD_SMESITEL": "Количество отверстий под смеситель",
  "KOLICHESTVO_POLOK": "Количество полок",
  "KOLICHESTVO_REZHIMOV_VERKHNEGO_DUSHA": "Количество режимов верхнего душа",
  "KOLICHESTVO_REZHIMOV_STRUI": "Количество режимов струи",
  "KOLICHESTVO_REZHIMOV_STRUI_VERKHNEGO_DUSHA": "Количество режимов струи верхнего душа",
  "KOLICHESTVO_REZHIMOV_STRUI_RUCHNOGO_DUSHA": "Количество режимов струи ручного душа",
  "KOLICHESTVO_SEKTSIY_DVEREY": "Количество секций дверей",
  "KOLICHESTVO_UPAKOVOK": "Количество упаковок",
  "KOLICHESTVO_FORSUNOK_AEROMASSAZHA": "Количество форсунок аэромассажа",
  "KOLICHESTVO_FORSUNOK_GIDROMASSAZHA": "Количество форсунок гидромассажа",
  "KOLICHESTVO_FORSUNOK_GIDROMASSAZHA_BOKOVOGO": "Количество форсунок гидромассажа бокового",
  "KOLICHESTVO_FORSUNOK_GIDROMASSAZHA_NOG": "Количество форсунок гидромассажа ног",
  "KOLICHESTVO_FORSUNOK_GIDROMASSAZHA_SPINY": "Количество форсунок гидромассажа спины",
  "KOLICHESTVO_CHASH": "Количество чаш",
  "KOLICHESTVO_YARUSOV": "Количество ярусов",
  "KOLICHESTVO_YASHCHIKOV": "Количество ящиков",
  "KOLICHESTVO_SHT": "Количество, шт.",
  "COLLECTION": "Коллекция",
  "NABOR": "Комплект",
  "KOMPLEKTATSIYA": "Комплектация",
  "KONSTRUKTSIYA": "Конструкция",
  "KORZINCHATYY_VENTIL_V_KOMPLEKTE": "Корзинчатый вентиль в комплекте",
  "KREPLENIYA": "Крепления",
  "KREPLENIYA_V_KOMPLEKTE": "Крепления в комплекте",
  "MATERIAL": "Материал",
  "MATERIAL_VERKHNEGO_DUSHA": "Материал верхнего душа",
  "MATERIAL_ZADNEY_STENKI": "Материал задней стенки",
  "MATERIAL_RAMY": "Материал инсталляции",
  "MATERIAL_KARKASA": "Материал каркаса",
  "MATERIAL_KNOPKI": "Материал кнопки",
  "MATERIAL_KORPUSA": "Материал корпуса",
  "MATERIAL_KREPLENIY": "Материал креплений",
  "MATERIAL_LEYKI_RUCHNOGO_DUSHA": "Материал лейки ручного душа",
  "MATERIAL_PODDONA": "Материал поддона",
  "MATERIAL_POKRYTIYA": "Материал покрытия корпуса",
  "MATERIAL_POKRYTIYA_STOLESHNITSY": "Материал покрытия столешницы",
  "MATERIAL_POKRYTIYA_FASADA": "Материал покрытия фасада",
  "MATERIAL_POLOTNA": "Материал полотна",
  "MATERIAL_PROFILYA": "Материал профиля",
  "MATERIAL_PEDESTALA": "Материал пьедестала",
  "MATERIAL_RAKOVINY": "Материал раковины",
  "MATERIAL_INTALYATSII": "Материал рамы",
  "MATERIAL_RESHETKI": "Материал решетки",
  "MATERIAL_RUCHEK": "Материал ручек",
  "MATERIAL_SIDENYA": "Материал сиденья",
  "MATERIAL_SIFONA": "Материал сифона",
  "MATERIAL_SLIVA": "Материал слива",
  "MATERIAL_STOLESHNITSY": "Материал столешницы",
  "MATERIAL_UNITAZA": "Материал унитаза",
  "MATERIAL_UPAKOVKI": "Материал упаковки",
  "MATERIAL_FASADA": "Материал фасада",
  "MATERIAL_TSENTRALNOY_STOYKI": "Материал центральной стойки",
  "MATERIAL_SHLANGA": "Материал шланга",
  "MEZHOSEVOE_RASSTOYANIE_POD_KREPEZHNYE_SHPILKI_MM": "Межосевое расстояние под крепежные шпильки, мм",
  "MEZHOSEVOE_RASSTOYANIE_MM": "Межосевое расстояние, мм",
  "METOD_POKRYTIYA": "Метод покрытия",
  "MEKHANIZM_SLIVA": "Механизм слива",
  "MEKHANIZM_SMESHIVANIYA": "Механизм смешивания",
  "MODEL": "Модель",
  "MODEL_RAKOVINY": "Модель раковины",
  "MONTAZH": "Монтаж",
  "MONTAZH_SLIVNOGO_BACHKA": "Монтаж сливного бачка",
  "MONTAZH_UNITAZA": "Монтаж унитаза",
  "MONTAZHNAYA_VYSOTA_MM": "Монтажная высота, мм",
  "MONTAZHNAYA_GLUBINA_MM": "Монтажная глубина, мм",
  "MONTAZHNAYA_DLINA_MM": "Монтажная длина, мм",
  "MONTAZHNAYA_SHIRINA_MM": "Монтажная ширина, мм",
  "MOSHCHNOST_VT": "Мощность, Вт",
  "NAGRUZKA_KG": "Нагрузка, кг",
  // "PRODUCT_NAME_ERP": "Название товара из 1с",
  "NAZVANIE_TSVETA": "Название цвета",
  "NAZNACHENIE": "Назначение",
  "NALICHIE_ZADNEY_STENKI": "Наличие задней стенки",
  "NALICHIE_ZERKALA": "Наличие зеркала",
  "NALICHIE_IZLIVA": "Наличие излива",
  "NALICHIE_INDIKATSII": "Наличие индикации",
  "NALICHIE_KRYLA": "Наличие крыла",
  "NALICHIE_KRYSHI": "Наличие крыши",
  "NALICHIE_PODDONA": "Наличие поддона",
  "NALICHIE_PODSVETKI": "Наличие подсветки",
  "NALICHIE_RAMY": "Наличие рамы",
  "NALICHIE_RUCHEK": "Наличие ручек",
  "NALICHIE_STOLESHNITSY": "Наличие столешницы",
  "NAMECHENNYE_OTVERSTIYA_POD_SMESITEL": "Намеченные отверстия под смеситель",
  "NAPRAVLENIE_VYPUSKA": "Направление выпуска",
  "NAPRYAZHENIE_V": "Напряжение, В",
  // "HIT": "Наши предложения",
  "NOZHKI_V_KOMPLEKTE": "Ножки в комплекте",
  "OBLAST_PRIMENENIYA": "Область применения",
  "OBORACHIVAEMAYA": "Оборачиваемая",
  "OBEM_BACHKA_L": "Объем бачка, л",
  "OBEM_VOZDUSHNOGO_POTOKA_M_MIN": "Объем воздушного потока, м³/мин",
  "OBEM_SMYVA_L": "Объем смыва, л",
  "OBEM_UPAKOVKI": "Объем упаковки, м³",
  "OBEM_L": "Объем, л",
  // "OPISANIE_DLYA_SAYTA": "Описание для сайта",
  "VID_SMYVAYUSHCHEGO_POTOKA": "Организация смывающего потока",
  "ORIENTATSIYA": "Ориентация",
  "ORIENTATSIYA_ZERKALA": "Ориентация зеркала",
  "OSNASHCHENIE": "Оснащение",
  "OSOBENNOSTI_GIDROMASSAZHA": "Особенности гидромассажа",
  "OSOBENNOSTI_ZERKALA": "Особенности зеркала",
  "OSOBENNOSTI_SIDENYA": "Особенности сиденья",
  "OTVERSTIE_POD_DOZATOR": "Отверстие под дозатор",
  "OTVERSTIE_POD_PERELIV": "Отверстие под перелив",
  "OTVERSTIE_POD_RAKOVINU": "Отверстие под раковину",
  "OTVERSTIYA_DLYA_MONTAZHA": "Отверстия для монтажа",
  "POVERKHNOST_KNOPKI": "Поверхность кнопки",
  "POVERKHNOST": "Поверхность корпуса",
  "POVERKHNOST_PROFILYA": "Поверхность профиля",
  "POVERKHNOST_RAKOVINY": "Поверхность раковины",
  "POVERKHNOST_RUCHEK": "Поверхность ручек",
  "POVERKHNOST_STOLESHNITSY": "Поверхность столешницы",
  "POVERKHNOST_UNITAZA": "Поверхность унитаза",
  "POVERKHNOST_FASADA": "Поверхность фасада",
  "PODACHA_PITEVOY_VODY": "Подача питьевой воды",
  "PODVOD_VODY": "Подвод воды",
  "podvodka": "Подводка",
  "PODKLYUCHENIE_K_FILTRU_DLYA_PITEVOY_VODY": "Подключение к фильтру для питьевой воды",
  "POKRYTIE_KARKASA": "Покрытие каркаса",
  "POLUPEDESTAL_V_KOMPLEKTE": "Полупьедестал в комплекте",
  "CML2_MANUFACTURER": "Производитель",
  "PROPUSKNAYA_SPOSOBNOST_SIFONA_L_MIN": "Пропускная способность сифона, л/мин",
  "PEDESTAL_V_KOMPLEKTE": "Пьедестал в комплекте",
  "RABOCHEE_DAVLENIE_BAR": "Рабочее давление, бар",
  "RAZMER_VERKHNEGO_DUSHA_MM": "Размер верхнего душа, мм",
  "RAZMER_LEYKI_RUCHNOGO_DUSHA_MM": "Размер лейки ручного душа, мм",
  "RAZMER_POSADOCHNOY_REZBY": "Размер посадочной резьбы",
  "RAZMER_SHTOKA_MM": "Размер штока, мм",
  "RAZMESHCHENIE": "Размещение",
  "RAKOVINA_V_KOMPLEKTE": "Раковина в комплекте",
  "RASPOLOZHENIE_VKHODA": "Расположение входа",
  "RASPOLOZHENIE_KRYLA": "Расположение крыла",
  "RASPOLOZHENIE_OTKRYTYKH_POLOK": "Расположение открытых полок",
  "RASPOLOZHENIE_PERELIVA": "Расположение перелива",
  "RASPOLOZHENIE_PETEL": "Расположение петель",
  "RASPOLOZHENIE_PODSVETKI": "Расположение подсветки",
  "RASPOLOZHENIE_RAKOVINY": "Расположение раковины",
  "RASPOLOZHENIE_SLIVA": "Расположение слива",
  "RASPOLOZHENIE_SMESITELYA": "Расположение смесителя",
  "RASPOLOZHENIE_STOLESHNITSY": "Расположение столешницы",
  "RASKHOD_VODY": "Расход воды",
  "REGULIROVKA": "Регулировка",
  "REGULIROVKA_PO_VYSOTE": "Регулировка по высоте",
  "REGULIROVKA_PO_VYSOTE_MM": "Регулировка по высоте, мм",
  "REGULIROVKA_PO_GLUBINE_MM": "Регулировка по глубине, мм",
  "REGULIROVKA_PO_SHIRINE_MM": "Регулировка по ширине, мм",
  "REZHIM_SLIVA_VODY": "Режим слива воды",
  "REKOMENDOVANNAYA_DLYA_KOMPLEKTATSII_RAKOVINA": "Рекомендованная для комплектации раковина",
  "RUCHKI_V_KOMPLEKTE": "Ручки в комплекте",
  "RUCHNOY_DUSH_V_KOMPLEKTE": "Ручной душ в комплекте",
  "S_DERZHATELEM_DLYA_DUSHEVOY_LEYKI": "С держателем для душевой лейки",
  "SIDENE_V_KOMPLEKTE": "Сиденье в комплекте",
  "SIDENE_S_KRYSHKOY": "Сиденье с крышкой",
  "SISTEMA_ANTIVSPLESK": "Система антивсплеск",
  "SISTEMA_KHRANENIYA": "Система хранения",
  "SIFON_V_KOMPLEKTE": "Сифон в комплекте",
  "SKOROST_VOZDUSHNOGO_POTOKA_M_S": "Скорость воздушного потока, м/с",
  "SKRYTYY_SLIV": "Скрытый слив",
  "SLIV_PERELIV_V_KOMPLEKTE": "Слив-перелив в комплекте",
  "SMESITEL_V_KOMPLEKTE": "Смеситель в комплекте",
  "SOVMESTIMOST": "Совместимость",
  "SOSTAV_NABORA": "Состав комплекта",
  // "DELIVERY_DAYS": "Срок поставки на склад",
  // "SSYLKA_NA_SERTIFIKATY_SOOTVETSTVIYA_DEKLARATSII_OT": "Ссылка на сертификаты соответствия, декларации, отказные письма",
  "STANDART_PODVODKI": "Стандарт подводки",
  "STIL": "Стиль",
  "STRANA_BRENDA": "Страна бренда",
  "STRANA_PROIZVODSTVA": "Страна производства",
  "TEMPERATURA_VOZDUSHNOGO_POTOKA_": "Цветовая температура, К",
  "TIP_VYKLYUCHATELYA": "Тип выключателя",
  "TIP_DIVERTORA": "Тип дивертора",
  "TIP_LAMPY": "Тип лампы",
  "TIP_MONTAZHA": "Тип монтажа",
  "TIP_PODVODKI": "Тип подводки",
  "TIP_SMESITELYA_DLYA_KOTOROGO_PODKHODIT": "Тип смесителя, для которого подходит",
  "TIP_TOVARA": "Тип товара",
  // "TIPY_TOVAROV_DLYA_KOTORYKH_PODKHODIT_S_SAYTA": "Типы товаров, для которых подходит, с сайта",
  "TOLSHCHINA_KARKASA_MM": "Толщина каркаса, мм",
  "TOLSHCHINA_LISTA_MM": "Толщина листа, мм",
  "TOLSHCHINA_POLOTNA_MM": "Толщина полотна, мм",
  "TOLSHCHINA_FASADA_MM": "Толщина фасада, мм",
  "TREBUETSYA_SISTEMA_INSTALLYATSII": "Требуется система инсталляции",
  "UGOL_POVOROTA_GRADUSY": "Угол поворота, градусы",
  "UNITAZ_V_KOMPLEKTE": "Унитаз в комплекте",
  "UPRAVLENIE": "Управление",
  "UROVEN_SHUMA_DB": "Уровень шума, Дб",
  "USTROYSTVO_SLIVA_V_KOMPLEKTE": "Устройство слива в комплекте",
  "UKHOD_ZA_IZDELIEM": "Уход за изделием",
  "FILES": "Файлы",
  "FILTR_DLYA_VODY_V_KOMPLEKTE": "Фильтр для воды в комплекте",
  "FORMA_VERKHNEGO_DUSHA": "Форма верхнего душа",
  "FORMA_KORPUSA": "Форма корпуса",
  "FORMA_LEYKI_RUCHNOGO_DUSHA": "Форма лейки ручного душа",
  "FORMA_PERELIVA": "Форма перелива",
  "FORMA_POSTAVKI": "Форма поставки",
  "FORMA_PEDESTALA": "Форма пьедестала",
  "FORMA_RAKOVINY": "Форма раковины",
  "FORMA_UNITAZA": "Форма унитаза",
  "FORMA_SHTOKA": "Форма штока",
  "CML2_ATTRIBUTES": "Характеристики",
  "TSVET": "Цвет",
  "TSVET_ZADNEY_STENKI": "Цвет задней стенки",
  "TSVET_KNOPKI": "Цвет кнопки",
  "TSVET_KORPUSA": "Цвет корпуса",
  "TSVET_PODSVETKI": "Цвет подсветки",
  "TSVET_POLOTNA": "Цвет полотна",
  "TSVET_PROFILYA": "Цвет профиля",
  "TSVET_PEDESTALA": "Цвет пьедестала",
  "TSVET_RAKOVINY": "Цвет раковины",
  "TSVET_RAMY": "Цвет рамы",
  "TSVET_RUCHEK": "Цвет ручек",
  "TSVET_SIDENYA": "Цвет сиденья",
  "TSVET_STOLESHNITSY": "Цвет столешницы",
  "TSVET_UNITAZA": "Цвет унитаза",
  "TSVET_FASADA": "Цвет фасада",
  "TSVET_FURNITURY": "Цвет фурнитуры",
  "TSVETOVAYA_TEMPERATURA_K": "Цветовая температура, К",
  "CHERTEZHY_I_SKHEMY": "Чертежи и схемы",
  "SHIRINA_VNESHNEY_CHASTI_MM": "Ширина внешней части, мм",
  "SHIRINA_VKHODA_MM": "Ширина входа, мм",
  "SHIRINA_DOPOLNITELNOY_CHASHI_MM": "Ширина дополнительной чаши, мм",
  "SHIRINA_INSTALLYATSII_MM": "Ширина инсталляции, мм",
  "SHIRINA_PEDESTALA_MM": "Ширина пьедестала, мм",
  "SHIRINA_UNITAZA_MM": "Ширина унитаза, мм",
  "SHIRINA_UPAKOVKI": "Ширина упаковки, м",
  "SHIRINA_CHASHI_MM": "Ширина чаши, мм",
  "SHIRINA": "Ширина, мм",
  "SHLANG_V_KOMPLEKTE": "Шланг в комплекте",
  "CML2_BAR_CODE": "ШтрихКод",
  // "SHTRIKHKOD": "Штрихкод",
  "EKRAN_V_KOMPLEKTE": "Экран в комплекте",
  // "PRODUCTS_IN_COLLECTION": "Товары в этой коллекции"
}

export type AttributesList = typeof attributesList

export default function mappedAttributes<K extends keyof AttributesList>(attributes: Attributes<K>) {
  const attrs: [string, string | number][] = [];
  attributes.forEach(attr => {
    if (attr.code in attributesList) {
      attrs.push([attr.name, attr.multiple ? attr.value.join(',') : attr.value]);
    }
  });
  return attrs
}
